# Generated by Django 1.9.13 on 2021-08-26 19:20
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0005_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
